version: '3'

services:
  
  seanstack-postgres:
    container_name: SEAN-STACK-Postgres
    image: postgres:latest
    enviroment:
      POSTGRES_PASSWORD: admin
    
  seanstack-express:
    container_name: SEAN-STACK-Express
    build: ./server
    volumes:
      - ./server:/opt/app
    ports:
      - 3000:3000
    depends_on:
      - meanstack-mongodb
  
  seanstack-angular:
    container_name: SEAN-STACK-Angular
    build: ./angular-app
    volumes:
      - ./angular-app:/opt/app
    ports:
      - 4200:4200
    depends_on:
      - meanstack-express